name: Go

on:
  push:
    branches:
      - main
      - addGithubActions
  pull_request:
    branches:
      - main
      - addGithubActions

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet ./...
        golint ./...

    - name: Test
      run: go test -v ./...


  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # changelog
      - name: Get Changelog
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ env.CURRENT_VERSION }}
          path: ./CHANGELOG.md
        # release
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false

  # release_notes:
  #   name: Create Release Notes
  #   runs-on: ubuntu-latest
  #   needs: changelog
  #   steps:
  #     - name: Get version from tag
  #       env:
  #         GITHUB_REF: ${{ github.ref }}
  #       run: |
  #         export CURRENT_VERSION=${GITHUB_TAG/refs\/tags\/v/}
  #         echo "::set-env name=CURRENT_VERSION::$CURRENT_VERSION"
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         ref: main

  #     - name: Get Changelog Entry
  #       id: changelog_reader
  #       uses: mindsers/changelog-reader-action@v1
  #       with:
  #         version: ${{ env.CURRENT_VERSION }}
  #         path: ./CHANGELOG.md

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: ${{ steps.changelog_reader.outputs.log_entry }}
  #         draft: false
  #         prerelease: false
