name: Go

on:
  push:
    branches:
      - main
      - addGithubActions
  pull_request:
    branches:
      - main
      - addGithubActions

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet -v ./...
        golint -v ./...

    - name: Test
      run: go test -v ./...
